In [12]:
import numpy as np

In [13]:
X=np.array([1,2,3,4,5])

In [14]:
X

array([1, 2, 3, 4, 5])

In [21]:
X=X.reshape(5,1)

In [22]:
Y=np.array([1,3,2,3,5])

In [23]:
Y

array([1, 3, 2, 3, 5])

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
teacher=LinearRegression()

In [26]:
learner=teacher.fit(X,Y)

In [27]:
learner.predict(1)

array([1.2])

In [28]:
learner.predict(3)

array([2.8])

In [29]:
learner.predict(5)

array([4.4])

In [30]:
learner.predict(4)

array([3.6])

In [31]:
learner.coef_

array([0.8])

In [32]:
learner.intercept_

0.39999999999999947