In [1]:
import numpy as np

In [9]:
x=np.array([1,2,3,4])

In [10]:
X=x.reshape(-1,1)

In [11]:
X

array([[1],
       [2],
       [3],
       [4]])

In [12]:
Y=([6,5,7,10])

In [13]:
Y

[6, 5, 7, 10]

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
teacher=LinearRegression()

In [16]:
learner=teacher.fit(X,Y)

In [17]:
learner.predict(1)

array([4.9])

In [18]:
learner.predict(2)

array([6.3])

In [19]:
learner.predict(3)

array([7.7])

In [20]:
learner.predict(4)

array([9.1])

In [22]:
m=learner.coef_

In [23]:
m

array([1.4])

In [24]:
learner.intercept_

3.4999999999999987