In [1]:
import pandas as pd

In [2]:
#for xlsx files we use excel as shown below 
uni=pd.read_excel(r"H:\machine learning\New Datasets\DataSets-master\DataSets-master\Uni_Data.xlsx")

In [3]:
uni

Input  Output
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

In [9]:
x=uni["Input"]

In [10]:
x

0     2.5
1     5.1
2     3.2
3     8.5
4     3.5
5     1.5
6     9.2
7     5.5
8     8.3
9     2.7
10    7.7
11    5.9
12    4.5
13    3.3
14    1.1
15    8.9
16    2.5
17    1.9
18    6.1
19    7.4
20    2.7
21    4.8
22    3.8
23    6.9
24    7.8
Name: Input, dtype: float64

In [12]:
y=uni["Output"]

In [14]:
y

0     21
1     47
2     27
3     75
4     30
5     20
6     88
7     60
8     81
9     25
10    85
11    62
12    41
13    42
14    17
15    95
16    30
17    24
18    67
19    69
20    30
21    54
22    35
23    76
24    86
Name: Output, dtype: int64

In [20]:
type(x)

pandas.core.series.Series

In [21]:
x.shape

(25,)

In [22]:
x.ndim

1

In [24]:
X=x.values.reshape(-1,1)

In [25]:
Y=y.values.reshape(-1,1)

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
teacher=LinearRegression()

In [28]:
learner=teacher.fit(X,Y)

In [29]:
x

0     2.5
1     5.1
2     3.2
3     8.5
4     3.5
5     1.5
6     9.2
7     5.5
8     8.3
9     2.7
10    7.7
11    5.9
12    4.5
13    3.3
14    1.1
15    8.9
16    2.5
17    1.9
18    6.1
19    7.4
20    2.7
21    4.8
22    3.8
23    6.9
24    7.8
Name: Input, dtype: float64

In [30]:
learner.predict(4.8)

array([[49.40752968]])

In [31]:
learner.predict(1.1)

array([[13.23705714]])

In [32]:
learner.predict(7.8)

array([[78.73493985]])

In [33]:
learner.predict(6.9)

array([[69.9367168]])

In [34]:
learner.coef_

array([[9.77580339]])

In [35]:
learner.intercept_

array([2.48367341])