In [18]:
import numpy as np

In [19]:
x=np.array([1,2,3,4,5,6,7])

In [20]:
x

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
x.reshape(7,)

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
X=x.reshape(-1,1)

In [42]:
type(x)

numpy.ndarray

In [43]:
X

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [44]:
Y=np.array([1,2,3,4,5,6,7])

In [46]:
Y


array([1, 2, 3, 4, 5, 6, 7])

In [29]:
y

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
teacher=LinearRegression()

In [47]:
leanear=teacher.fit(X,Y)

In [48]:
leanear.coef_

array([1.])

In [51]:
leanear.intercept_

0.0

In [52]:
X.shape

(7, 1)

In [53]:
leanear.predict(1)

array([1.])

In [54]:
leanear.predict(7)

array([7.])