In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5])

In [3]:
x

array([1, 2, 3, 4, 5])

In [4]:
x.reshape(5,)

array([1, 2, 3, 4, 5])

In [5]:
X=x.reshape(-1,1)

In [6]:
type(X)

numpy.ndarray

In [7]:
X

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
Y=np.array([1,3,2,3,5])

In [9]:
Y

array([1, 3, 2, 3, 5])

In [10]:
X

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
teacher=LinearRegression()

In [14]:
learner=teacher.fit(X,Y)

In [15]:
learner.coef_

array([0.8])

In [16]:
X.shape

(5, 1)

In [17]:
learner.intercept_

0.39999999999999947

In [18]:
learner.predict(1)

array([1.2])