In [11]:
import numpy as np

In [12]:
R=np.array([3,5,6,2,7])

In [13]:
R

array([3, 5, 6, 2, 7])

In [15]:
R=R.reshape(5,1)

In [16]:
R

array([[3],
       [5],
       [6],
       [2],
       [7]])

In [8]:
p=np.array([1,4,3,9,5])

In [9]:
p

array([1, 4, 3, 9, 5])

In [18]:
from sklearn.linear_model import LinearRegression

In [27]:
teacher=LinearRegression()

In [28]:
lenear=teacher.fit(R,p)

In [32]:
lenear.predict(1)

array([5.90697674])

In [33]:
lenear.predict(4)

array([4.65116279])

In [34]:
lenear.predict(3)

array([5.06976744])

In [35]:
lenear.predict(9)

array([2.55813953])

In [36]:
lenear.predict(5)

array([4.23255814])

In [38]:
lenear.coef_

array([-0.41860465])

In [40]:
lenear.intercept_

6.325581395348837